name: Update GitHub Contributions

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC
  push:
    branches:
      - main             # Run on push to main
  pull_request:
    branches:
      - main             # Run when PR is merged into main
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-contributions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install Playwright
      run: |
        pip install playwright
        playwright install chromium

    - name: Fetch and save contributions
      run: python .github/scripts/fetch_contributions.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add assets/images/contributions.json
        git commit -m "Update GitHub contributions [automated]" || echo "No changes to commit"
        git push
